### ISSUE TITLE
No longer works with DLC

### ISSUE THREAD

**Issue by steffbo** [amfor/brotato_mac_port#3]
With the Abyssal Terrors DLC, the command
```
./steamcmd.sh +@sSteamCmdForcePlatformType windows +force_install_dir $MAC_GAME_FOLDER +login $STEAM_USERNAME $STEAM_PASSWORD $STEAM_CODE +app_update $APP_ID validate +exit
```
no longer works. I get a steam popup saying "invalid platform"

**Comment by amfor** [comment]
Seems like it may have broken compatibility for the base game as well. I pushed an [update](https://github.com/amfor/brotato_mac_port/commit/3749fe48d86a9490bcd8bdbc61e821d0d0aa555a) to at least preserve base game functionality, albeit it's a bit outdated. 

SteamCMD didn't let me download from the [compat](https://steamdb.info/app/1942280/depots/?branch=v1.1.0.0-compat) branch.

I don't think this is a matter of godot being out of date either, but I bumped it just to be sure. 

It might involve mods not loading, although this was an issue in prior versions as well

```
INFO ModLoader:ThirdParty:Steam: Checking workshop items, with path: "workshop/content/"
Can't open workshop folder workshop/content/ (Error: 31)
ERROR: Can't open workshop folder workshop/content/ (Error: 31)
   at: call (modules/gdscript/gdscript_functions.cpp:775)
INFO ModLoader: No zipped mods found
WARNING ModLoader: Can't open unpacked mods folder res://mods-unpacked/.
WARNING: Can't open unpacked mods folder res://mods-unpacked/.
     at: call (modules/gdscript/gdscript_functions.cpp:789)
INFO ModLoader: No mods were setup
SUCCESS ModLoader: DONE: Loaded all meta data
SUCCESS ModLoader: DONE: Completely finished loading mods
SUCCESS ModLoader: DONE: Installed all script extensions

```

**Comment by amfor** [comment]
A fork which fixed this was merged in today. You should be able to enjoy the DLC now. 

It consists of de-compiling the game, removing incompatible portions, and re-compiling it.
